import type { Metadata } from 'next';
import { Zen_Kurenaido } from 'next/font/google';
import './globals.css';
import React from 'react';

const zenKurenaido = Zen_Kurenaido({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-zenKurenaido',
});

export const metadata: Metadata = {
  title: "takumi's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${zenKurenaido.variable}`}>
      <body>{children}</body>
    </html>
  );
}
