name: CI
# "CI"という名前のワークフローを定義しています。

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
# ワークフローは、"main"ブランチへのプッシュやプルリクエスト、または手動での実行時にトリガーされます。

jobs:
  build:
    runs-on: ubuntu-latest
# "build"という名前のジョブを定義し、最新のUbuntuランナー上で実行されるように設定しています。

    steps:
      - uses: actions/checkout@v3
# リポジトリのコードをチェックアウトし、ジョブが実行されるワークスペースにアクセスできるようにします。

      - name: Run a one-line script
        run: echo Hello, world!
# "Hello, world!"と出力する単一行のスクリプトを実行します。

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
# 複数行のスクリプトを実行し、ビルド、テスト、デプロイに関する他のアクションを追加する例を示します。
